name: Clippy & Test & Build

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches: ['main']

env:
    CARGO_TERM_COLOR: always

jobs:
    clippy:
        name: clippy
        runs-on: ${{ matrix.os }}
        env:
            RUSTFLAGS: -D warnings
        strategy:
            matrix:
                toolchain:
                    - stable
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        steps:
            - uses: actions/checkout@v4
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - run: cargo clippy --all-targets --all-features -- -D warnings

    test:
        name: test
        needs: clippy
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                toolchain:
                    - stable

        steps:
            - uses: actions/checkout@v4
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - run: cargo test --verbose

    build:
        name: build
        needs: test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                toolchain:
                    - stable
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        steps:
            - uses: actions/checkout@v4
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - run: cargo build --verbose
